#pragma checksum "C:\Users\User-PC\Documents\GitHub\Pin-STARWARS\PIN\Views\Home\Contact.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1abb966199d411082d9695c8a22d13a54dce30ab"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Contact), @"mvc.1.0.view", @"/Views/Home/Contact.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/Contact.cshtml", typeof(AspNetCore.Views_Home_Contact))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Users\User-PC\Documents\GitHub\Pin-STARWARS\PIN\Views\_ViewImports.cshtml"
using PIN;

#line default
#line hidden
#line 2 "C:\Users\User-PC\Documents\GitHub\Pin-STARWARS\PIN\Views\_ViewImports.cshtml"
using PIN.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"1abb966199d411082d9695c8a22d13a54dce30ab", @"/Views/Home/Contact.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"8acfc84a6fa17acce34705c13606dcb58cadfdd1", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Contact : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/images/a/123.jpg"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("height", new global::Microsoft.AspNetCore.Html.HtmlString("350"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("width", new global::Microsoft.AspNetCore.Html.HtmlString("450"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 1 "C:\Users\User-PC\Documents\GitHub\Pin-STARWARS\PIN\Views\Home\Contact.cshtml"
  
    ViewData["Title"] = "About Star Wars";

#line default
#line hidden
            BeginContext(51, 8105, true);
            WriteLiteral(@"<h2>About: </h2>
<p>
    Star Wars is an American epic space opera franchise, created by George Lucas and centered around a film series that began with the eponymous 1977 movie. The saga quickly became a worldwide pop culture phenomenon.

    The first film was followed by two successful sequels, The Empire Strikes Back (1980) and Return of the Jedi (1983); these three films constitute the original Star Wars trilogy. A prequel trilogy was released between 1999 and 2005, albeit to mixed reactions from critics and fans. Finally, a sequel trilogy to conclude the nine-episode saga began in 2015 with The Force Awakens. The first eight films were nominated for Academy Awards (with wins going to the first two released) and were commercially successful, with a combined box office revenue of over US$8.5 billion. Together with the theatrical spin-off films The Clone Wars (2008), Rogue One (2016), and Solo: A Star Wars Story (2018), Star Wars is the second-highest-grossing film series of all time.

    The film se");
            WriteLiteral(@"ries has spawned into other media, including books, television shows, computer and video games, theme park attractions and lands, and comic books, resulting in significant development of the series' fictional universe. Star Wars holds a Guinness World Records title for the ""Most successful film merchandising franchise"". In 2018, the total value of the Star Wars franchise was estimated at US$65 billion, and it is currently the fifth-highest-grossing media franchise.
</p>
<h2>Overview:</h2>
<p>
    The Star Wars story has been presented in a series of American films, which have spawned a large quantity of books and other media, which have formed the Expanded Universe. The Star Wars mythos is also the basis of many toys and games of varying types. The films and novels employ common science-fiction motifs.

    Whereas Gene Roddenberry's Star Trek, a science fantasy franchise that has enjoyed long-lasting popularity in American popular culture, is portrayed by its makers to appear as a rational and progress");
            WriteLiteral(@"ive approach to storytelling, Star Wars has a strong mythic quality alongside its political and scientific elements.

    Unlike the heroes of earlier space-set sci-fi/fantasy film and TV series such as Flash Gordon, the heroes of Star Wars are not militaristic types but romantic individualists. College literature professors have remarked that the Star Wars saga, with its struggle between good and evil, democracy and empire, can be considered a national epic for the United States. The film has many visual and narrative similarities to John Ford's The Searches, which also provides a clue to the relationship between Leia Organa and Luke Skywalker.

    The strong appeal of the Star Wars story probably accounts for its enduring popularity; it has also been postulated that this popularity is based on nostalgia. Many Star Wars fans first saw the films as children, and the revolutionary (for the time) special effects and simple, Manichean story made a profound impact.

    The Star Wars films show considerabl");
            WriteLiteral(@"e similarity to Japanese Jidaigeki films, as well as Roman mythology. Lucas has stated that his intention was to create in Star Wars a modern mythology, based on the studies of his friend and mentor Joseph Campbell. He has also called the first movie's similarity to the film The Hidden Fortress (Akira Kurosawa) an ""homage.""

    The Star Wars films portray a world full of grime and technology that looks like it has been used for years, unlike the sleek, futuristic world typical of earlier science-fiction films. In interviews, Lucas tells of rubbing the new props with dirt to make them look weatherworn. Lucas may have been inspired by the Sergio Leone Spaghetti Western films of the 1960s, which performed a similar function on the Western many years earlier. It is tempting to speculate that this break from traditional science-fiction film influenced the cyberpunk genre that emerged around 1984.

    Licensed Star Wars novels have been published since the original movie was released in 1977. Although these n");
            WriteLiteral(@"ovels are licensed by Lucas (meaning he shares in the royalties), he retains ultimate creative control over the Star Wars universe, forcing Lucas Licensing to devote considerable ongoing effort to ensuring continuity between different authors' works and Lucas' films. Occasionally, elements from these novels are adopted into the highest tier of Star Wars canon, the movies. Books, games, and stories that are not directly derived from the six movies of Star Wars are known as the Extended or Expanded Universe (EU for short). Lucas has said that he does not deeply involve himself in the EU, choosing instead to concentrate mainly on his movies instead of ""…the licensing world of the books, games and comic books.""

    The original (1977) Star Wars (A New Hope) has been selected for preservation in the United States National Film Registry.

    In 1978, Lucas sued the creators of Battlestar Galactica for its similarity to Star Wars. The case was dismissed as having no merit in 1980 by a U.S. Federal judge.
</p>");
            WriteLiteral(@"
<h2>Conception:</h2>
<p>
    Many different influences have been suggested for the Star Wars films by fans, critics, and George Lucas himself. Lucas acknowledges that the plot and characters in the 1958 Japanese film The Hidden Fortress, directed by Akira Kurosawa, was a major inspiration. Lucas has said that the movie influenced him to tell the story of Star Wars from the viewpoint of the humble droids, rather than a major player. It also played a role in the conception of Darth Vader, whose trademark black helmet intentionally resembles a samurai helmet.

    George Lucas has often said that his original idea for the project that evolved into Star Wars was to remake the Flash Gordon movie serials from the 1930s (a ""serial"" is a movie shown in weekly installments of about 10-20 minutes each). The license wasn't available, so Lucas moved on to other ideas, beginning with Akira Kurosawa's film The Hidden Fortress and then Joseph Campbell's The Hero With a Thousand Faces. Despite the plot changes the Star");
            WriteLiteral(@" Wars films are still bursting with influences from the Flash Gordon movie serials, including the Rebels vs. the Imperial Forces, Cloud City and even the famous ""roll up"" which begins the movie.

    The second major direction for Star Wars (used in the 1973 synopsis) was to use the Flash Gordon ""vocabulary"" to create an outer-space version of the Samurai films of Akira Kurosawa, primarily Kakushi toride no san akunin (The Hidden Fortress, 1958), Tsubaki Sanjūrō (Sanjuro, 1962) and Yojimbo (1961). Joseph Campbell's The Hero With a Thousand Faces eventually gave Lucas a third and final major story direction, but many elements from Kurosawa's work remain, including the two bickering peasants (who evolved into the droids), and the queen who often switches places with her handmaiden. The Darth Vader-like evil general who has a change of heart at the end wears a kamon (a Japanese family crest) that looks very similar to the Japanese Imperial Crest.

    Lucas had already written two drafts of Star Wars when he");
            WriteLiteral(@" rediscovered Joseph Campbell's The Hero With a Thousand Faces in 1975 (having read it years before in college). This blueprint for ""The Hero's Journey"" gave Lucas the focus he needed to draw his sprawling imaginary universe into a single story. Campbell demonstrates in his book that all stories are expressions of the same story-pattern, which he named the Hero's Journey or the monomyth.

    Lucas has often cited The Lord of the Rings series as a major influence on Star Wars. Lucas learned from Tolkien how to handle the delicate stuff of myth. Tolkien wrote that myth and fairytale seem to be the best way to communicate morality - hints for choosing between right and wrong - and in fact that may be their primary purpose. Lucas has also acknowledged in interviews that the Gandalf and the Witch-king characters in the Lord of the Rings influenced the Obi-Wan Kenobi and Darth Vader characters respectively.
</p>


<center>");
            EndContext();
            BeginContext(8156, 55, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "d9d7244e990a46a28eda19179034ed01", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(8211, 10, true);
            WriteLiteral(" </center>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
